server:
  port: 80
  servlet:
    context-path: /demo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmfz
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    time-zone:  GMT+8
    date-format: yyyy-MM-dd
  redis:
    database: 0
    host: 192.168.26.15
    port: 3372
mybatis:
  mapper-locations: com/baizhi/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity
logging:
  level:
    root: error
    com.baizhi.dao: debug